[tool.poetry]
name = "nro45-merge"
version = "0.1.0"
description = "Merge MAO datasets observed with NRO 45m telescope into a single netCDF file"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fire = "^0.4"

[tool.poetry.dev-dependencies]
black = "^20.8b"
flake8 = "^3.8"
ipython = "^7.20"
pytest = "^6.2"

[tool.poetry.scripts]
nro45-merge = "nro45_merge.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
