name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    env:
      TESTED_DIRS: nro45_merge tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install pandoc
          pip install poetry
          poetry install
      - name: Test code format (Black)
        run: poetry run black --check ${TESTED_DIRS}
      - name: Test code style (Flake8)
        run: poetry run flake8 ${TESTED_DIRS}
      - name: Test package (pytest)
        run : poetry run pytest -v tests
      - name: Test docs building (Sphinx)
        run: poetry run docs/build
